package trabalho.locadora;

import java.util.*;
import java.io.*;

/**
 *
 * @author user
 */
public class CarrosDisponveis extends javax.swing.JInternalFrame {

    String modelos[] = {};
    ArrayList<carro> Frota;
    int numeroCarro;

    public CarrosDisponveis() throws FileNotFoundException {
        Frota=carro.getfrota();
        numeroCarro=carro.getNumeroCarros();
        
        String Modelos[] = new String[numeroCarro];
        for (int i = 0; i < numeroCarro; i++) {
            Modelos[i] = Frota.get(i).modelo;
        }
        modelos = Modelos;
        initComponents();
        
        String aux = "";
        marca.setText(Frota.get(0).marca);
        cor.setText(Frota.get(0).cor);
        placa.setText(Frota.get(0).placa);
        aux = Frota.get(0).kmAndado + "";
        km.setText(aux);
        aux = "";
        aux = Frota.get(0).preco + "";
        preco.setText(aux);

        if (Frota.get(0).disponivel == 0) {
            disponivel.setText("nao");
        } else {
            disponivel.setText("sim");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_list = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jPanel_info = new javax.swing.JPanel();
        jLabel_placa = new javax.swing.JLabel();
        jLabel_Cor = new javax.swing.JLabel();
        jLabel_Marca = new javax.swing.JLabel();
        jLabel_km = new javax.swing.JLabel();
        jLabel_preco = new javax.swing.JLabel();
        jLabel_disponivel = new javax.swing.JLabel();
        jScrollPane_placa = new javax.swing.JScrollPane();
        placa = new javax.swing.JTextPane();
        jScrollPane_cor = new javax.swing.JScrollPane();
        cor = new javax.swing.JTextPane();
        jScrollPane_km = new javax.swing.JScrollPane();
        km = new javax.swing.JTextPane();
        jScrollPane_marca = new javax.swing.JScrollPane();
        marca = new javax.swing.JTextPane();
        jScrollPane_disponivel = new javax.swing.JScrollPane();
        disponivel = new javax.swing.JTextPane();
        jScrollPane_preco = new javax.swing.JScrollPane();
        preco = new javax.swing.JTextPane();
        jLabel_ordenar = new javax.swing.JLabel();
        jButton_ordenar_km = new javax.swing.JButton();
        jButton_ordenar_preco = new javax.swing.JButton();
        jButton_ordenar_alphabetic = new javax.swing.JButton();

        setClosable(true);

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = modelos;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListValueChanged(evt);
            }
        });
        jScrollPane_list.setViewportView(jList);

        jLabel_placa.setText("Placa:");

        jLabel_Cor.setText("Cor:");

        jLabel_Marca.setText("Marca:");

        jLabel_km.setText("Klometragem:");

        jLabel_preco.setText("preço:");

        jLabel_disponivel.setText("disponibilidade:");

        jScrollPane_placa.setViewportView(placa);

        jScrollPane_cor.setViewportView(cor);

        jScrollPane_km.setViewportView(km);

        jScrollPane_marca.setViewportView(marca);

        jScrollPane_disponivel.setViewportView(disponivel);

        jScrollPane_preco.setViewportView(preco);

        jLabel_ordenar.setText("Organizar por:");

        jButton_ordenar_km.setText("Klometragem");

        jButton_ordenar_preco.setText("Preço");

        jButton_ordenar_alphabetic.setText("Alfabetica");

        javax.swing.GroupLayout jPanel_infoLayout = new javax.swing.GroupLayout(jPanel_info);
        jPanel_info.setLayout(jPanel_infoLayout);
        jPanel_infoLayout.setHorizontalGroup(
            jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addComponent(jLabel_disponivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane_disponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Marca)
                            .addComponent(jLabel_Cor)
                            .addComponent(jLabel_placa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane_cor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jScrollPane_marca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_placa))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_infoLayout.createSequentialGroup()
                                .addComponent(jLabel_preco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 36, Short.MAX_VALUE))
                            .addGroup(jPanel_infoLayout.createSequentialGroup()
                                .addComponent(jLabel_km)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane_km))))
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_infoLayout.createSequentialGroup()
                                .addComponent(jButton_ordenar_km)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_ordenar_preco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_ordenar_alphabetic))
                            .addComponent(jLabel_ordenar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_infoLayout.setVerticalGroup(
            jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_placa)
                            .addComponent(jScrollPane_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Cor)
                            .addComponent(jScrollPane_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Marca)
                            .addComponent(jScrollPane_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_preco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_km))))
                .addGap(43, 43, 43)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_disponivel)
                    .addComponent(jScrollPane_disponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel_ordenar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ordenar_km)
                    .addComponent(jButton_ordenar_preco)
                    .addComponent(jButton_ordenar_alphabetic))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane_list, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_list, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListValueChanged
        String aux = "";
        marca.setText(Frota.get(jList.getSelectedIndex()).marca);
        cor.setText(Frota.get(jList.getSelectedIndex()).cor);
        placa.setText(Frota.get(jList.getSelectedIndex()).placa);
        aux = Frota.get(jList.getSelectedIndex()).kmAndado + "";
        km.setText(aux);
        aux = "";
        aux = Frota.get(jList.getSelectedIndex()).preco + "";
        preco.setText(aux);

        if (Frota.get(jList.getSelectedIndex()).disponivel == 0)
            disponivel.setText("nao");
        else
            disponivel.setText("sim");
    }//GEN-LAST:event_jListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane cor;
    private javax.swing.JTextPane disponivel;
    private javax.swing.JButton jButton_ordenar_alphabetic;
    private javax.swing.JButton jButton_ordenar_km;
    private javax.swing.JButton jButton_ordenar_preco;
    private javax.swing.JLabel jLabel_Cor;
    private javax.swing.JLabel jLabel_Marca;
    private javax.swing.JLabel jLabel_disponivel;
    private javax.swing.JLabel jLabel_km;
    private javax.swing.JLabel jLabel_ordenar;
    private javax.swing.JLabel jLabel_placa;
    private javax.swing.JLabel jLabel_preco;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel_info;
    private javax.swing.JScrollPane jScrollPane_cor;
    private javax.swing.JScrollPane jScrollPane_disponivel;
    private javax.swing.JScrollPane jScrollPane_km;
    private javax.swing.JScrollPane jScrollPane_list;
    private javax.swing.JScrollPane jScrollPane_marca;
    private javax.swing.JScrollPane jScrollPane_placa;
    private javax.swing.JScrollPane jScrollPane_preco;
    private javax.swing.JTextPane km;
    private javax.swing.JTextPane marca;
    private javax.swing.JTextPane placa;
    private javax.swing.JTextPane preco;
    // End of variables declaration//GEN-END:variables
}
