/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho.locadora;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class MenuPrincipal extends javax.swing.JFrame {
    ArrayList<carro> Frota;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() throws FileNotFoundException {
        Frota = new ArrayList<>();
        File arquivo = new File("C:\\Users\\user\\Desktop\\lixo\\trabalho-OO\\carros.txt");
        Scanner leitura = new Scanner(arquivo);

        String dados = "";
        int numeroCarro = 0;
        int contador = 0;
        while (leitura.hasNextLine()) {

            dados = dados + leitura.nextLine() + '\n';
            contador++;
            if (contador == 8) {
                contador = 0;
                carro veiculo = new carro(dados);
                Frota.add(veiculo);
                dados = "";
                numeroCarro++;
            }
        }
        carro.setfrota(Frota);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_TodaFrota = new javax.swing.JMenuItem();
        jMenuItem_carrosLivres = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_vender = new javax.swing.JMenuItem();
        jMenuItem_comprar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        jMenuBar.setName("Menu"); // NOI18N

        jMenu1.setText("Carros");

        jMenuItem_TodaFrota.setText("Toda Frota");
        jMenuItem_TodaFrota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TodaFrotaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_TodaFrota);

        jMenuItem_carrosLivres.setText("Carros Livres");
        jMenuItem_carrosLivres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_carrosLivresActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_carrosLivres);

        jMenuBar.add(jMenu1);

        jMenu2.setText("Funcionarios");

        jMenuItem8.setText("Lista de Funcionarios");
        jMenu2.add(jMenuItem8);

        jMenuItem10.setText("Demitir Funcionario");
        jMenu2.add(jMenuItem10);

        jMenuItem9.setText("Contratar Funcionario");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar.add(jMenu2);

        jMenu3.setText("Clientes");

        jMenuItem5.setText("Clientes Cadastrados");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Adicionar Cliente");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Remover Cliente");
        jMenu3.add(jMenuItem7);

        jMenuBar.add(jMenu3);

        jMenu4.setText("Garagem");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem_vender.setText("Vender/Editar");
        jMenuItem_vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_venderActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_vender);

        jMenuItem_comprar.setText("Comprar");
        jMenuItem_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_comprarActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_comprar);

        jMenuBar.add(jMenu4);

        jMenu5.setText("Perfil");
        jMenuBar.add(jMenu5);

        setJMenuBar(jMenuBar);
        jMenuBar.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_carrosLivresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_carrosLivresActionPerformed
        CarrosDisponveis Carros = null;     
        
        try {
            Carros = new CarrosDisponveis();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        jDesktopPane1.add(Carros);
        Carros.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_carrosLivresActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem_TodaFrotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TodaFrotaActionPerformed
        TodaFrota frota = null;

        try {
            frota = new TodaFrota();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(frota);
        frota.setVisible(true);

    }//GEN-LAST:event_jMenuItem_TodaFrotaActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem_venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_venderActionPerformed
        GaragemCarros frota = null;
        try {
            frota = new GaragemCarros();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(frota);
        frota.setVisible(true);
    }//GEN-LAST:event_jMenuItem_venderActionPerformed

    private void jMenuItem_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_comprarActionPerformed
        
        CompraDeCarro telaCompra;
        telaCompra = new CompraDeCarro();
        jDesktopPane1.add(telaCompra);
        telaCompra.setVisible(true);
    }//GEN-LAST:event_jMenuItem_comprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuPrincipal().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem_TodaFrota;
    private javax.swing.JMenuItem jMenuItem_carrosLivres;
    private javax.swing.JMenuItem jMenuItem_comprar;
    private javax.swing.JMenuItem jMenuItem_vender;
    // End of variables declaration//GEN-END:variables
}
